export const customerSupport = [
  "Size guides",
  "Shipping",
  "Returns",
  "Track my order",
];
export const myAccount = [
  "Order history",
  "Payment methods",
  "Account settings",
  "Favorites",
];
export const categories = [
  "Jackets & Outwear",
  "Tops",
  "T-shirts",
  "Shirts & Blouses",
  "Dresses",
  "Jeans & Trousers",
  "Skirts & Shorts",
  "Jeans & Trousers",
  "Skirts & Shorts",
];
export const sizes = [
  "32 (XXS)",
  "34 (XS)",
  "36 (S)",
  "38 (M)",
  "40 (L)",
  "42 (XL)",
  "44 (XXL)",
  "46 (3XL)",
];
export const color = [
  "pink",
  "yellow",
  "green",
  "blak",
  "gray",
  "white",
  "burgundy",
  "red",
  "orange",
  "blue",
  "liBlue",
  "purple",
];
export const brands = [
  "Abercrombie & Fitch",
  "Acca Kappa",
  "Accessorize",
  "Adidas",
  "Aeropostale",
  "Asics",
  "BIKKEMBERGS",
  "Bogner",
  "BOSS",
  "Buffalo",
  "Buxom",
  "Braintropy",
  "Calliope",
  "Calvin Klein",
  "Champion",
  "Chi Modu",
  "Collaboraid",
  "Converce",
  "Crocs",
  "Diadora",
  "Diesel",
  "DKNY",
  "Don The Fuller",
  "Dr. Martens",
  "Ellesse",
  "Esprit",
  "Etro",
  "Fenty",
  "Fila",
  "Forever 21",
  "Funko Pop",
  "Gucci",
  "Helly Hansen",
  "Hermes",
  "Herschel",
  "Hummel",
  "Hugo Boss",
  "Hollister",
  "Louis Vuitton",
  "Maje",
  "Mamalicious",
  "Michael Kors",
  "Missguided",
  "Miss Sixty",
  "Monki",
  "Na KD",
  "Napapijri",
  "Neon Rose",
  "New Balance",
  "New Era",
  "New Look",
  "Nike",
  "Nine West",
  "Noisy May",
  "Nylon",
  "Only",
  "Oskia",
  "Obey",
  "Olivia Burton",
  "Oasis",
  "Ouai",
  "One Above Another",
  "Orelia",
  "Palladium",
  "People Tree",
  "Pepe Jeans",
  "Pilgrim",
  "Pimkie",
  "Polo Ralph Lauren",
  "Pretty Little Thing",
  "Puma",
  "Quay",
  "Quiksilver",
  "Raga",
  "Ray-Ban",
  "Rebecca Minkoff",
  "Reiss",
  "Replay",
  "Rip Curl",
  "River Island",
  "Roxy",
  "Saint Genies",
  "Sam Edelman",
  "SAVAGE X FENTY",
  "Selfie",
  "SIMMI",
  "Sister Jane",
  "Sole East by Onia",
  "Sorel",
  "Steve Madden",
  "Stradivarius",
  "Superdry",
  "Ted Baker",
  "The Girlcode",
  "The Laundress",
  "Timberland",
  "Tommy Hilfiger",
  "Topshop",
  "True Religion",
  "Ugg",
  "Under Armor",
  "UOMA",
  "Urbancode",
  "Vagabond",
  "Vans",
  "Vesper",
  "Volcom",
  "Von Dutch",
  "Warehouse",
  "Weekday",
  "WISHFUL",
  "WMNS WEAR",
  "Wolf & Whistle",
  "Wrangler",
  "Y.A.S.",
  "Yours",
  "Zara",
  "Zulu & Zephyr",
  "ZYA",
  "& Other Stories",
  "4th & Reckless",
];
